[versions]
androidxCore = "1.12.0"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
testJunit = "1.1.5"
espresso = "3.5.1"
activity = "1.7.2"

agp = "8.1.0"
kotlin = "1.9.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

firebase-database = { module = "com.google.firebase:firebase-database-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleGmsGoogleServices = { id = "com.google.gms.google-services", version = "4.4.0" }